services:
  - type: web
    name: fer-proj-api
    env: python
    plan: free
    region: oregon


    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
