name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Basic check
      run: |
        echo "Build successful"

    - name: Build Docker image
      run: |
        docker build -t fer-project .

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: |
        docker tag fer-project ${{ secrets.DOCKER_USERNAME }}/fer-project:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fer-project:latest    
